[WIP] use Clang integrated assembler
Simspace/ld-wrapper-macos pull request #5
Opened 2020-11-16 18:28 UTC by peterbecich

Appears to solve warning

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../libexec/as/x86_64/as: this system assembler is deprecated.  Please migrate to the clang integrated assembler ('as -q').
```

2020-11-16 19:18 UTC, beefyhalo requested changes
Cool! Just left a small change request.

2020-11-16 19:18 UTC, beefyhalo commented on ld64.ld-wrapper-macos.sh
>      # `-Q` means use GNU Assembler rather than Clang, avoiding an awkward
Update this comment to match `-q` (or delete?)

2020-11-16 19:39 UTC, peterbecich commented on ld64.ld-wrapper-macos.sh
>      # `-Q` means use GNU Assembler rather than Clang, avoiding an awkward
nice catch, improved

2020-11-16 22:18 UTC, beefyhalo approved these changes
🎉

2020-11-17 15:24 UTC, jship reviewed
Oof, I forget the context on the old comment about intentionally avoiding the Clang assembler due to a dep cycle. @peterbecich, would you mind running the build over the [example repo](https://github.com/Simspace/ld-wrapper-macos#example) to see if things look good?

2020-11-18 09:03 UTC, peterbecich commented
will check, thanks

2020-11-20 05:01 UTC, peterbecich commented
@jship , this PR's version of the script appears to succeed

First attempt
```
ld (lib)
Preprocessing library for panic-0.0.0..
Building library for panic-0.0.0..
[1 of 3] Compiling Paths_panic
[2 of 3] Compiling Th
[3 of 3] Compiling Lib
ghc: panic! (the 'impossible' happened)
  (GHC version 8.2.2 for x86_64-apple-darwin):
	Loading temp shared object failed: dlopen(/var/folders/s4/64h2cy3d19s1jp25vv5_sn0w0000gp/T/ghc15278_0/libghc_13.dylib, 5): no suitable image found.  Did find:
	/var/folders/s4/64h2cy3d19s1jp25vv5_sn0w0000gp/T/ghc15278_0/libghc_13.dylib: malformed mach-o: load commands size (159064) > 32768
	/var/folders/s4/64h2cy3d19s1jp25vv5_sn0w0000gp/T/ghc15278_0/libghc_13.dylib: stat() failed with errno=25

Please report this as a GHC bug:  http://www.haskell.org/ghc/reportabug

Completed 221 action(s).

```

Second attempt, with `ld-wrapper-macos`

```
Configuring panic-0.0.0...
clang: warning: argument unused during compilation: '-no-pie' [-Wunused-command-line-argument]
panic> build (lib)
Preprocessing library for panic-0.0.0..
Building library for panic-0.0.0..
[3 of 3] Compiling Lib
panic> copy/register
Installing library in ...
Registering library for panic-0.0.0..
```

2020-11-20 15:08 UTC, jship commented
Woot, let's merge it 🚀

2020-11-20 15:08 UTC, merged